name: Daily - Do npm install and run all unit tests

on:
  workflow_dispatch:
  schedule:
    # run daily at midnight
    - cron: '0 0 * * *'

jobs:
  build:
    uses: adobe/aio-reusable-workflows/.github/workflows/daily.yml@main