name: publish-prerelease
on:
  workflow_dispatch:
    inputs:
      pre-release-tag:
        description: 'The pre-release tag use in the version'
        required: false
        default: 'pre'
      dist-tag:
        description: 'The dist-tag use'
        required: false
        default: 'next'
      dependencies-to-update:
        description: 'csv of dependencies to update with the dist-tag'
        required: false
        default: '@adobe/aio-lib-analytics,@adobe/aio-lib-campaign-standard,@adobe/aio-lib-customer-profile,@adobe/aio-lib-events,@adobe/aio-lib-files,@adobe/aio-lib-state,@adobe/aio-lib-target,@adobe/aio-sdk-core'

jobs:
  checkout:
    uses: adobe/aio-reusable-workflows/.github/workflows/prerelease.yml@main